### ISSUE TITLE
SuperTux 0.6.2 released 

### ISSUE THREAD

**Issue by pixelr0** [lotharsm/supertux-snapcraft#1]
SuperTux 0.6.2 released  https://www.supertux.org/news/2020/05/14/0.6.2

**Comment by lotharsm** [comment]
Thanks for the heads up, I just triggered a re-build of the snap. As soon as launchpad finished building them, I'll promote the builds to stable.

**Comment by lotharsm** [comment]
I just released 0.6.2 to the stable channel, it should be available in a couple of minutes.

In fact, I had an error in the snapcraft.yaml file, so it failed to automagically build the 0.6.2 release as "nightly" build - seems to be fixed now. So - thanks again!

**Comment by pixelr0** [comment]
thank you! o/
